language: groovy
jdk:
  - oraclejdk7
install: true
env:
  - TERM=dumb
script:
  - ./gradlew check
after_success:
  - ./gradlew cobertura coveralls
after_failure: find build/reports/tests -name "*.html" -exec grep -A 10 "Condition not satisfied" {} \;
